import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { join } from 'node:path';
import { chapterNames, chapterColors, esc, planSvg, pathLength, distance } from './render.mjs';

const root = fileURLToPath(new URL('../../', import.meta.url));
const out = join(root, 'public/level-design');
await mkdir(join(out, 'sheets'), { recursive: true });
const plans = (await Promise.all(Object.keys(chapterNames).map(c => readFile(join(root, `docs/level-design/plans/${c}.json`), 'utf8').then(JSON.parse)))).flat();
const css = await readFile(new URL('./style.css', import.meta.url), 'utf8');
const client = await readFile(new URL('./viewer.js', import.meta.url), 'utf8');

const list = (items, cls = '') => `<ul class="${cls}">${items.map(s => `<li>${esc(s)}</li>`).join('')}</ul>`;
function detail(p) {
  const route = p.mainRoute.map(id => p.passages.find(e => e.id === id));
  const length = route.reduce((n, e) => n + pathLength(e), 0);
  const loops = p.passages.length - p.rooms.length + 1;
  return `<article class="sheet" data-plan="${p.id}" hidden>
    <header class="sheet-heading"><div><p class="eyebrow">${esc(chapterNames[p.chapter])} / ${String(p.index).padStart(2,'0')} ${p.index === 5 ? ' · 首领关' : ' · 探索与交战'}</p><h1>${esc(p.title)}</h1><p class="subtitle">${esc(p.subtitle)}</p></div><div class="sheet-actions"><a class="download play-link" href="/whitebox-lab.html?theme=${p.chapter}&amp;stage=${p.index - 1}&amp;look=art">场景试玩与白盒对照 ↗</a><a class="download" href="sheets/${p.id}.svg" download>下载 SVG 图纸 ↗</a></div></header>
    <div class="sheet-grid"><section class="drawing" aria-label="关卡平面图"><div class="drawing-bar"><span>俯视平面 · 平层方案</span><span>${p.bounds[0]} × ${p.bounds[1]} m · 网格 5 m</span></div>${planSvg(p)}<div class="legend"><span><i class="main-line"></i>推荐主路</span><span><i class="optional-line"></i>可选路线</span><span><i class="return-line"></i>回接通道</span><span><b class="enemy-key">A</b>小队阵位 / 朝向</span><span><b class="reward-key">◆</b>物资</span><span><b class="cover-key">▧</b>实体遮挡 2.6m</span><span><b class="portal-key">S → X</b>入口 → 出口</span></div><p class="drawing-note">浅色区域可行走，蓝灰区域不可通行。蓝线标示主路通道，房间内自由移动。阵位为战术区域中心；红虚线为设计射线。通道标注为地面宽度，通行尺度沿用已试玩白盒，场景美术覆盖后继续复测净空与射线。</p></section>
    <aside class="brief"><p class="identity">${esc(p.identity)}</p><dl class="metrics"><div><dt>空间节点</dt><dd>${p.rooms.length}</dd></div><div><dt>通道网络回路</dt><dd>${loops}</dd></div><div><dt>通道宽度</dt><dd>${Math.min(...p.passages.map(e=>e.width))}–${Math.max(...p.passages.map(e=>e.width))}<small>m</small></dd></div></dl>
    <section><h2>这一关让玩家做什么</h2><p>${esc(p.objective)}</p></section><section><h2>选路的代价</h2><p>${esc(p.routeChoice)}</p></section>
    <section><h2>行进节奏</h2><ol class="beats">${p.pacing.map(s=>`<li>${esc(s)}</li>`).join('')}</ol></section>
    <p class="metric-note">主路连接段约 ${Math.round(length)}m，另计房内移动；不是通关时间。所有尺寸沿用本项目已试玩白盒的设计值。</p></aside></div>
    <div class="review-grid"><section><h2>怪物与空间一起设计</h2><p>${esc(p.encounterLogic)}</p><div class="encounter-list">${p.encounters.map(e=>`<article><b class="encounter-id">${esc(e.id.length > 2 ? "首" : e.id)}</b><div><h3>${esc(e.label)}</h3><p>${esc(e.roster)}</p><p class="muted">${esc(e.timing)}</p></div></article>`).join('')}</div></section>
    <section><h2>通道安排</h2><table><thead><tr><th>连接</th><th>宽</th><th>意图</th></tr></thead><tbody>${p.passages.map(e=>`<tr><td>${esc(p.rooms.find(r=>r.id===e.from).label)} → ${esc(p.rooms.find(r=>r.id===e.to).label)}</td><td>${e.width}m</td><td>${esc(e.note)}</td></tr>`).join('')}</tbody></table></section>
    <section><h2>美术阶段继续复测的问题</h2>${list(p.whiteboxChecks)}<h2>场景美术的空间约束</h2><p>${esc(p.artBrief)}</p><h3>重点射线</h3>${list(p.sightlines.map(l=>`${l.label} · ${distance(l.from,l.to).toFixed(1)}m`))}</section></div>
    <footer class="sheet-footer">LD-02 / ${p.id.toUpperCase()} · 2026-10-04 · 场景美术阶段 · 15 关布局与 Hunyuan 场景已作为正常游戏默认 · 实战平衡持续验证</footer></article>`;
}

const nav = Object.entries(chapterNames).map(([id,label])=>`<section class="chapter" style="--chapter:${chapterColors[id]}"><h2>${label}</h2>${plans.filter(p=>p.chapter===id).map(p=>`<button data-select="${p.id}" aria-pressed="false"><span>${String(p.index).padStart(2,'0')}</span><strong>${esc(p.title)}</strong>${p.index===5?'<em>B</em>':''}</button>`).join('')}</section>`).join('');
const gallery = Object.entries(chapterNames).map(([id,label])=>`<section class="gallery-chapter"><h2>${label}</h2><div class="contact-row">${plans.filter(p=>p.chapter===id).map(p=>`<button class="contact" data-select="${p.id}">${planSvg(p,{compact:true,fixedScale:true,suffix:'-small'})}<span class="contact-title">${p.index}. ${esc(p.title)}</span><span>${esc(p.subtitle)}</span></button>`).join('')}</div></section>`).join('');
const method = `<section class="method" data-view="method" hidden><p class="eyebrow">设计依据 / 验证边界</p><h1>先验证空间，再投入美术。</h1><p class="lead">十五张独立平面图已完成技术白盒接入，并获得用户试玩认可。当前进入场景美术阶段：15 关布局与 Hunyuan 场景已作为正常游戏默认；每关可直接进入场景试玩，并切换技术白盒对照原通道与遮挡。</p><div class="process"><article><b>01</b><h2>目标与节奏</h2><p>先确定玩家要观察、选路、换位或压制什么；以遭遇与休整组织空间。</p></article><article><b>02</b><h2>平面布局 · 已成稿</h2><p>画可走地面、连接宽度、遮挡、阵位和奖励，检查每条支路的收益与风险。</p></article><article><b>03</b><h2>白盒试玩 · 已认可</h2><p>15 关白盒已接入真实移动与遭遇，用户试玩认可后进入美术阶段。通行、识路、射线与战斗继续作为复测依据。</p></article><article><b>04</b><h2>场景美术 · 当前</h2><p>按已试玩的空间装配本机 Hunyuan3D 资产，完善每关轮廓、地标、材质与灯光；保留通道、碰撞尺度与适度面数。</p></article></div>
    <h2>用本游戏的尺度，不把经验数值当作行业标准</h2><table><thead><tr><th>依据</th><th>当前代码</th><th>图纸上的应用</th></tr></thead><tbody><tr><td>角色体积</td><td>半径 0.35m / 身高 1.8m / 视点 1.62m</td><td>尺寸检查用角色半径；遮挡体初定 2.6m。</td></tr><tr><td>移动与冲刺</td><td>基础 7.5m/s；冲刺 22m/s × 0.18s ≈ 3.96m</td><td>主战通道通常 6–8m，短侧路可用 4m；冲刺后的惯性未计入约 4m。</td></tr><tr><td>巫祝</td><td>保持 13–21m；法阵半径 3.5m</td><td>房内保留横移区域，侧通道能接近施法者，避免在窄口承受整组法阵。</td></tr><tr><td>炮手 / 狙击手</td><td>保持 15–27m / 18–32m</td><td>炮手需要压近路线；狙线需遮挡与绕行。实体掩体不能保证阻挡曲射。</td></tr></tbody></table>
    <h2>图纸检查与后续验收</h2>${list(['二维检查：房间—通道图连通，主路首尾完整；通道中心线避开实体遮挡；入口、出口、阵位和奖励落在可走区。','运行时几何 6 项测试通过：真实 1m NavGrid 精确到达 178 个检查点，玩家实体按行走与冲刺速度通过，通道双向通行、首领出生净空和外围阻挡通过检查。','美术覆盖后继续复测：第一人称下能否读懂下一目标；敌人能否换位；掩体是否造成卡位；炮击预警有没有足够躲避空间。','遭遇已按图配置：分区触发、安全阵位、刷新预警与单场战斗互锁。流程 6 项测试覆盖 15 张普通/首领图、12 个精英分支及 30 个商店/宝藏情形；自动化调度通过不等于战斗平衡通过。','普通/精英分支已沿用各自关卡底图并调整编队；商店/宝藏已保留该图空间骨架、移除战斗并安排商人或奖励。正常游戏已默认使用这 15 张布局及 Hunyuan 场景，试玩页保留技术白盒对照。','白盒按 0.5m 格采样，斜边误差最多约 0.36m；掩体高 2.6m，外围碰撞高 8m；技术白盒与碰撞一致，Hunyuan 场景按其空间边界装配。当前统一平层，坡道、高台与跨层射线需另做剖面验证。'])}
    <h2>实机行走记录</h2><p>浏览器内用真实移动控制器走过沙寺第 1 关的一条路线，记录 132.2m / 17.2s。该数值是具体路线的行走记录，并非通关时间；十五关的第一人称可读性与实战平衡仍在逐项验证。</p>
    <h2>参考方法</h2><p>常见流程会先做草图、节点关系与灰盒，再用实际角色验证尺度和视线；没有一套适用于所有游戏的固定平面模板。</p><p><a href="https://dev.epicgames.com/documentation/unreal-engine/designer-01-project-setup-and-level-blockout-in-unreal-engine?lang=en-US" target="_blank" rel="noreferrer">Epic：草图、尺度、遮挡与关卡白盒 ↗</a></p><p><a href="https://book.leveldesignbook.com/process/blockout" target="_blank" rel="noreferrer">The Level Design Book：白盒与反复试玩 ↗</a></p><p class="muted">移动参数来源：PlayerController.ts、Stats.ts；敌人尺度来源：Mortar.ts、Marksman.ts、Shaman.ts。未以图纸检查代替可玩性结论。</p></section>`;

const html = `<!doctype html><html lang="zh-CN"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>灵火破晓 · 关卡平面设计图册</title><style>${css}</style></head><body><a class="skip" href="#workspace">跳到图纸</a><header class="topbar"><a href="#desert-1" class="brand">灵火破晓 <span>关卡设计室</span></a><nav aria-label="图册视图"><button data-mode="detail" aria-pressed="true">逐关图纸</button><button data-mode="gallery" aria-pressed="false">15 关同尺度对比</button><button data-mode="method" aria-pressed="false">设计依据</button></nav><button id="print">打印图册</button></header><div class="workbench"><aside class="sidebar"><div class="revision"><span>LD—02</span><p>平面图与场景美术<br>保留白盒对照复测</p></div><nav aria-label="选择关卡">${nav}</nav><p class="sidebar-note">每章 5 关 · 共 15 关<br>蓝图尺寸以米为单位</p></aside><main id="workspace"><div class="status"><span class="status-dot"></span>当前：场景美术<span>白盒试玩已认可 · 15 关已作为游戏默认</span></div><div class="layerbar" data-view="detail"><span>显示图层</span>${[['routes','路线'],['encounters','怪物与奖励'],['sightlines','设计射线'],['dimensions','通道尺寸'],['labels','区域名称']].map(([id,label])=>`<label><input type="checkbox" data-toggle="${id}" checked>${label}</label>`).join('')}</div><div data-view="detail">${plans.map(detail).join('')}</div><section class="gallery" data-view="gallery" hidden><p class="eyebrow">空间轮廓 / 横向审图</p><h1>十五关 · 空间布局总览</h1><p class="lead">全部按相同单位比例绘制。比较入口与出口、空间串联方式和不可通行区；点击任一图查看通道与怪物安排。</p>${gallery}<p class="gallery-note">S 入口 · X 出口 · 蓝线主路 · 绿线支路 · 紫线回接 · ◆ 物资。每格为同样大小的 150m × 150m 图幅。</p></section>${method}<footer class="global-footer">灵火破晓 / 关卡平面设计 · 2026.10.04 <span>图纸版本 LD—02</span></footer></main></div><script>${client}</script></body></html>`;
await writeFile(join(out, 'index.html'), html);
for (const p of plans) {
  const inner = planSvg(p).replace(/^<svg[^>]+>/,'').replace(/<\/svg>$/,'');
  const w = p.bounds[0]+8, h=p.bounds[1]+8;
  const exportSvg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h+21}" role="img"><title>${esc(p.title)}平面图</title><rect width="${w}" height="${h+21}" fill="#edf2f5"/><text style="text-anchor:start" x="4" y="5" font-family="Microsoft YaHei,sans-serif" font-size="3" fill="#294455">${esc(p.title)} / ${esc(p.subtitle)}</text><text style="text-anchor:start" x="4" y="9" font-family="Microsoft YaHei,sans-serif" font-size="1.7" fill="#526978">${p.bounds[0]}×${p.bounds[1]}m · 网格5m · 平层底图 · 白盒试玩已认可 · 场景美术阶段</text><g transform="translate(0 12)">${inner}</g><text style="text-anchor:start" x="4" y="${h+16}" font-family="Microsoft YaHei,sans-serif" font-size="1.65" fill="#294455">S入口 / X出口 · 蓝主路 / 绿支路 / 紫回接 · 红字小队阵位 · ◆物资</text><text style="text-anchor:start" x="4" y="${h+19}" font-family="Microsoft YaHei,sans-serif" font-size="1.65" fill="#294455">浅色可行走 / 蓝灰不可通行 · 斜线实体遮挡2.6m · 通道数字=宽度(m)</text></svg>`;
  await writeFile(join(out, `sheets/${p.id}.svg`), exportSvg);
}
console.log(`Built ${plans.length} authored floor plans and atlas: ${out}`);
