import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';

const root = fileURLToPath(new URL('../../', import.meta.url));
const plans = (await Promise.all(['desert', 'frost', 'inferno'].map(chapter =>
  readFile(resolve(root, `docs/level-design/plans/${chapter}.json`), 'utf8').then(JSON.parse),
))).flat();
const output = `// Generated by scripts/level-plans/sync-runtime.mjs. Edit docs/level-design/plans/*.json instead.\nimport type { WhiteboxPlan } from './WhiteboxTypes';\n\nexport const WHITEBOX_PLANS: readonly WhiteboxPlan[] = ${JSON.stringify(plans, null, 2)};\n`;
const target = resolve(root, 'src/world/WhiteboxPlans.ts');
if (process.argv.includes('--check')) {
  const actual = (await readFile(target, 'utf8')).replace(/\r\n/g, '\n');
  if (actual !== output) throw new Error('WhiteboxPlans.ts differs from reviewed floor-plan JSON. Run node scripts/level-plans/sync-runtime.mjs.');
  console.log(`Whitebox runtime plans match all ${plans.length} reviewed floor plans.`);
} else {
  await writeFile(target, output, 'utf8');
  console.log(`Synced ${plans.length} authored floor plans to src/world/WhiteboxPlans.ts.`);
}
