"""Register the TravelDeck numeric capture reference and native ImageGen pixels.

The panel is captured upright to expose its walkable surface to four-view
projection. The existing Blender presentation transform lays it horizontal.
No artistic mesh or placeholder GLB is generated by this registration script.
"""
from __future__ import annotations
import argparse
import json
import os
import shutil
import sys
from pathlib import Path

os.environ['ART_PIPELINE_SKIP_ENV'] = '1'
from PIL import Image
from lib.config import CFG
from lib.state import AssetState, sha256
from lib import imaging
from prepare_nature_batch import reference_data, register_panels

ID = 'SM_Env_TravelDeck'


def prepare():
    spec = CFG.asset(ID)
    state = AssetState(spec)
    meta, _ = reference_data(spec)
    # Blender original X/Y/Z = game X/-Z/Y. Presentation turns original
    # positive Z thickness toward -Y and original +Y length upward.
    # Capture feet sit at presentation Z=0. Runtime recenters actual bounds.
    meta['bounds'] = {'min': [-3, 0, -4], 'max': [3, 0.7, 0]}
    views = {
        'panel': [512, 1024],
        'views': [dict(view=name, dir=direction, right=right, up=[0, 0, 1],
                       center=[0, -0.35, 2], world_w=6.72, world_h=13.44,
                       px_w=512, px_h=1024)
                  for name, direction, right in [
                      ('front', [0, 1, 0], [1, 0, 0]),
                      ('left', [-1, 0, 0], [0, 1, 0]),
                      ('back', [0, -1, 0], [-1, 0, 0]),
                      ('right', [1, 0, 0], [0, -1, 0])]],
        'bbox_min': [-3, -0.7, 0], 'bbox_max': [3, 0, 4],
        'presentation': [[1, 0, 0], [0, 0, -1], [0, 1, 0]],
        'reference_mode': 'bounds_only',
    }
    current = state.current('blockout')
    if current:
        stem = f"BO_{ID}_v{current['version']:03d}"
        if (json.loads(state.file(current, stem+'.json').read_text(encoding='utf8')) == meta
                and json.loads(state.file(current, stem+'_views.json').read_text(encoding='utf8')) == views):
            return state, current, views
    version = state.next_version('blockout')
    stem = f'BO_{ID}_v{version:03d}'
    out = spec.stage_dir('blockout')
    files = [out/(stem+'.json'), out/(stem+'_views.json')]
    for file, data in zip(files, [meta, views]):
        file.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding='utf8')
    record = state.add_version('blockout', dict(version=version, source=meta['source'],
        joints=0, bounds=meta['bounds'], reference_mode='bounds_only', geometry_created=False,
        capture_presentation='upright deck, front is walkable top; standard Blender rotation only'), files)
    return state, record, views


def register(source_json: Path):
    state, bo, views = prepare()
    spec = CFG.asset(ID)
    item = json.loads(source_json.read_text(encoding='utf8'))
    assert item['id'] == ID and item['prompt'].strip()
    source = Path(item['path']).resolve()
    current = state.current('concept')
    digest = sha256(source)
    if current and current.get('source_sha256') == digest and current.get('from_blockout') == bo['version']:
        print('CONCEPT_UNCHANGED', ID)
        return
    with Image.open(source) as image:
        panels, registration = register_panels(image.convert('RGBA'), views, 4.0)
    version = state.next_version('concept')
    stem = f'CN_{ID}_v{version:03d}'
    out = spec.stage_dir('concept')
    native = out/(stem+'_source'+source.suffix)
    shutil.copyfile(source, native)
    files, panel_paths = [native], []
    for name, panel in zip(imaging.VIEW_ORDER, panels):
        file = out/(stem+'_'+name+'.png')
        panel.save(file)
        files.append(file)
        panel_paths.append(file)
    sheet = out/(stem+'_sheet.png')
    imaging.compose_row(panel_paths, sheet)
    prompt = out/(stem+'_prompt.txt')
    prompt.write_text(item['prompt'], encoding='utf8')
    alignment = out/(stem+'_registration.json')
    alignment.write_text(json.dumps(registration, indent=2), encoding='utf8')
    files.extend([sheet, prompt, alignment])
    state.add_version('concept', dict(version=version, from_blockout=bo['version'],
        generator='Codex built-in image_gen', source_image=str(source), source_sha256=digest,
        prompt=item['prompt'], reference_mode='bounds_only', highpoly_mode='multiview',
        registration_version=1, registration=registration), files)
    print('CONCEPT_READY_FOR_REVIEW', ID, sheet)


if __name__ == '__main__':
    sys.stdout.reconfigure(encoding='utf8')
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--concept', required=True, type=Path)
    register(parser.parse_args().concept)
